FROM node:22-alpine

WORKDIR /app

# workspace manifests
COPY package.json package-lock.json ./
COPY apps/frontend/package.json ./apps/frontend/package.json

# install workspace dependencies
RUN npm ci

EXPOSE 3000

WORKDIR /app/apps/frontend

CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]
