FROM node:24-alpine

WORKDIR /app

COPY package*.json ./
COPY apps/frontend/package.json ./apps/frontend/package.json

RUN npm install

COPY . .

WORKDIR /app/apps/frontend

CMD ["npm", "run", "dev"]
