FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/backend/package.json ./apps/backend/package.json

RUN npm ci

WORKDIR /app/apps/backend

EXPOSE 3001

CMD ["npm", "run", "start:dev"]
