FROM node:24-alpine

WORKDIR /app

COPY package*.json ./
COPY apps/backend/package.json ./apps/backend/package.json

RUN npm install

COPY . .

WORKDIR /app/apps/backend

CMD ["npm", "run", "start:dev"]
