import * as fs from 'fs';
import * as path from 'path';

import { COMPANY, SEED_PASSWORD, TEAM, PROJECTS, USERS } from './seed-config';

// Must stay inside apps/backend — that is the only folder the seed container
// shares with your machine.
const TARGET = path.resolve(__dirname, '../../docs/TEST-CREDENTIALS.md');

export function writeCredentialsFile(): string {
  const rows = USERS.map(
    (user) =>
      `| ${user.role} | \`${user.email}\` | ${user.firstName} ${user.lastName} | ${user.note} |`,
  ).join('\n');

  const projects = PROJECTS.map(
    (project) => `- **${project.name}** — ${project.members.join(', ')}`,
  ).join('\n');

  const content = `# Test logins

Generated by \`make seed\`. Do not edit by hand — change
\`apps/backend/src/seed/seed-config.ts\` and re-seed instead.

**Every account below uses the same password:**

\`\`\`
${SEED_PASSWORD}
\`\`\`

Sign in at http://localhost:3000/login

## Accounts

All of them belong to the single test company **${COMPANY.companyName}**.

| Role | Email | Name | What it is for |
| :--- | :--- | :--- | :--- |
${rows}

## Team "${TEAM.name}"

${TEAM.members.map((m) => `- ${m.email} (${m.roleInTeam})`).join('\n')}

Anyone not listed here is invisible to the manager — that is deliberate, and it
is how you check the role-visibility rules by hand.

## Project members

${projects}

> This file contains a password, so it is not committed: the repository ignores
> \`*.md\` by default. Re-run \`make seed\` to recreate it.
`;

  fs.writeFileSync(TARGET, content, 'utf8');

  return TARGET;
}
