import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";

import "./globals.css";

import Providers from "./providers";
import { AdminSidebar } from "./components/admin/AdminSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen">
        <Providers>
          <div className="flex h-full flex-col md:flex-row">
            <AdminSidebar />

            <main className="flex-1 h-full overflow-y-auto bg-gray-50">
              {children}
            </main>
          </div>

          <Toaster richColors position="top-right" />
        </Providers>
      </body>
    </html>
  );
}
